name: 🐛 Bug Report
description: Report a bug
labels: ["type: bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["Critical", "High", "Medium", "Low"]
