name: ✨ Feature Request
description: Propose a new feature
labels: ["type: feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["Critical", "High", "Medium", "Low"]
